In [4]:
# PS - Movie Dataset Operations

import pandas as pd

# Load Dataset
movies = pd.read_csv("movies_metadata.csv", low_memory=False)
ratings = pd.read_csv("ratings_small.csv")

# 1. Clean + Merge

movies = movies[movies["id"].astype(str).str.isnumeric()]
movies["id"] = movies["id"].astype(int)

avg = ratings.groupby("movieId")["rating"].mean().reset_index()
avg.columns = ["id", "rating"]

df = pd.merge(movies, avg, on="id")

# Keep only useful columns
df = df[[
    "id",
    "title",
    "original_language",
    "rating",
    "vote_average",
    "vote_count"
]]

print("Original Dataset")
display(df.head())

# 2. Subsets

english = df[df["original_language"] == "en"]
french = df[df["original_language"] == "fr"]

print("English Movies")
display(english.head())

# 3. Merge Subsets

merged = pd.concat([english, french])

print("Merged Data")
display(merged.head())

# 4. Sort Data

sorted_data = df.sort_values(by="rating", ascending=False)

print("Sorted Data")
display(sorted_data.head())

# 5. Transpose

print("Transpose Data")
display(df.head().T)

# 6. Melt

melted = pd.melt(
    df.head(),
    id_vars=["id", "title"],
    var_name="attribute",
    value_name="value"
)

print("Melted Data")
display(melted.head())

# 7. Pivot Table

pivot = df.pivot_table(
    values="rating",
    index="original_language",
    aggfunc="mean"
)

print("Pivot Table")
display(pivot)

Original Dataset

,id,title,original_language,rating,vote_average,vote_count
0,949,Heat,en,3.593750,7.7,1886.0
1,710,GoldenEye,en,1.500000,6.6,1194.0
2,1408,Cutthroat Island,en,3.616279,5.7,137.0
3,524,Casino,en,3.555556,7.8,1343.0
4,4584,Sense and Sensibility,en,5.000000,7.2,364.0

English Movies

,id,title,original_language,rating,vote_average,vote_count
0,949,Heat,en,3.593750,7.7,1886.0
1,710,GoldenEye,en,1.500000,6.6,1194.0
2,1408,Cutthroat Island,en,3.616279,5.7,137.0
3,524,Casino,en,3.555556,7.8,1343.0
4,4584,Sense and Sensibility,en,5.000000,7.2,364.0

Merged Data

,id,title,original_language,rating,vote_average,vote_count
0,949,Heat,en,3.593750,7.7,1886.0
1,710,GoldenEye,en,1.500000,6.6,1194.0
2,1408,Cutthroat Island,en,3.616279,5.7,137.0
3,524,Casino,en,3.555556,7.8,1343.0
4,4584,Sense and Sensibility,en,5.000000,7.2,364.0

Sorted Data

,id,title,original_language,rating,vote_average,vote_count
17,2086,Nick of Time,en,5.0,6.1,190.0
2830,49280,The One-Man Band,fr,5.0,6.5,22.0
2810,64278,Interceptor Force 2,fr,5.0,0.0,0.0
2778,26797,Denis Leary: No Cure for Cancer,en,5.0,7.1,19.0
55,2636,The Specialist,en,5.0,5.5,317.0

Transpose Data

,0,1,2,3,4
id,949,710,1408,524,4584
title,Heat,GoldenEye,Cutthroat Island,Casino,Sense and Sensibility
original_language,en,en,en,en,en
rating,3.59375,1.5,3.616279,3.555556,5.0
vote_average,7.7,6.6,5.7,7.8,7.2
vote_count,1886.0,1194.0,137.0,1343.0,364.0

Melted Data

     id                  title          attribute value
0   949                   Heat  original_language    en
1   710              GoldenEye  original_language    en
2  1408       Cutthroat Island  original_language    en
3   524                 Casino  original_language    en
4  4584  Sense and Sensibility  original_language    en

Pivot Table

                     rating
original_language
bn                 3.819444
bs                 2.964286
cn                 3.630128
cs                 3.492978
da                 3.405659
de                 3.356460
en                 3.337308
es                 3.159204
et                 4.261905
fa                 3.972222
fi                 3.348919
fr                 3.288677
he                 3.579762
hi                 3.446749
hu                 3.363636
it                 3.260845
ja                 3.197947
ka                 4.000000
kk                 3.750000
ko                 3.674163
mn                 3.432390
nl                 3.373271
no                 3.888889
pl                 3.322139
pt                 3.426430
ro                 3.235294
ru                 3.543802
sr                 3.833333
sv                 3.081103
ta                 4.500000
te                 3.500000
th                 3.398944
tl                 2.500000
tr                 3.708333
uk                 3.000000
xx                 3.318182
zh                 3.339711
zu                 3.037037